name: Deploy to VPS (Staging)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List workspace contents
      run: ls -la ${{ github.workspace }}

    - name: Setup SSH Keys
      uses: shivammathur/ssh-key@v4
      with:
        key: ${{ secrets.VPS_SSH_KEY }}
        name: id_rsa # This is the default name and it will work for most cases
        known_hosts: ${{ secrets.VPS_HOST }}

    - name: Debug SSH connection
      run: ssh -v -o StrictHostKeyChecking=no ${VPS_USERNAME}@${VPS_HOST} "ls /var/www/server"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: "rsync -r --delete-after ${{ github.workspace }} /var/www/server"