name: Deploy to VPS (Staging)

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List workspace contents
      run: ls -la ${{ github.workspace }}

    - name: Debug SSH connection
      run: |
        echo "${{ secrets.VPS_SSH_KEY }}" > /tmp/deploy_key
        chmod 600 /tmp/deploy_key
        ls -la /tmp/deploy_key
        cat /tmp/deploy_key
        ssh -v -i /tmp/deploy_key ${VPS_USERNAME}@${VPS_HOST} "ls /var/www/server"

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: "rsync -r --delete-after ${{ github.workspace }} /var/www/server"